set-option -g escape-time 0
set-option -g mouse off
set-option -g history-limit 50000
set-window-option -g mode-keys vi

# only exit via CTRL-D on the third try
set-environment -g 'IGNOREEOF' 2

# allow terminal title to pass through to window
set-option -g set-titles on
set-option -g set-titles-string '#T'

# fix neovim
set-option -g focus-events on
set-option -sa terminal-features ',xterm-256color:RGB'

# shift window numbers when erased
set-option -g renumber-windows on
set-option -g display-time 0

# change prefix to <Ctrl>-s
unbind-key C-b
set-option -g prefix C-s
bind-key C-s send-prefix

# key bindings
bind-key j select-pane -D
bind-key k select-pane -U
bind-key h select-pane -L
bind-key l select-pane -R
bind-key c new-window -c '#{pane_current_path}'
bind-key q set-option -g mouse off \; display-message "Mouse: Off"
bind-key Q set-option -g mouse on \; display-message "Mouse: On"
bind-key | split-window -h -c '#{pane_current_path}'
bind-key - split-window -v -c '#{pane_current_path}'
